default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: simulador_brasileirao_development

test:
  <<: *default
  database: simulador_brasileirao_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
