default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: vagrant
  password: vagrant
  host: localhost

development:
  <<: *default
  database: simulador-brasileirao_development

test:
  <<: *default
  database: simulador-brasileirao_test

production:
  <<: *default
  database: simulador-brasileirao_production
